/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SkincareRouteImport } from './routes/skincare'
import { Route as HairBodyRouteImport } from './routes/hair-body'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AccessoriesRouteImport } from './routes/accessories'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductProductIdRouteImport } from './routes/product.$productId'

const SkincareRoute = SkincareRouteImport.update({
  id: '/skincare',
  path: '/skincare',
  getParentRoute: () => rootRouteImport,
} as any)
const HairBodyRoute = HairBodyRouteImport.update({
  id: '/hair-body',
  path: '/hair-body',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessoriesRoute = AccessoriesRouteImport.update({
  id: '/accessories',
  path: '/accessories',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductProductIdRoute = ProductProductIdRouteImport.update({
  id: '/product/$productId',
  path: '/product/$productId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessories': typeof AccessoriesRoute
  '/blog': typeof BlogRoute
  '/catalog': typeof CatalogRoute
  '/contact': typeof ContactRoute
  '/hair-body': typeof HairBodyRoute
  '/skincare': typeof SkincareRoute
  '/product/$productId': typeof ProductProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessories': typeof AccessoriesRoute
  '/blog': typeof BlogRoute
  '/catalog': typeof CatalogRoute
  '/contact': typeof ContactRoute
  '/hair-body': typeof HairBodyRoute
  '/skincare': typeof SkincareRoute
  '/product/$productId': typeof ProductProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessories': typeof AccessoriesRoute
  '/blog': typeof BlogRoute
  '/catalog': typeof CatalogRoute
  '/contact': typeof ContactRoute
  '/hair-body': typeof HairBodyRoute
  '/skincare': typeof SkincareRoute
  '/product/$productId': typeof ProductProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accessories'
    | '/blog'
    | '/catalog'
    | '/contact'
    | '/hair-body'
    | '/skincare'
    | '/product/$productId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accessories'
    | '/blog'
    | '/catalog'
    | '/contact'
    | '/hair-body'
    | '/skincare'
    | '/product/$productId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/accessories'
    | '/blog'
    | '/catalog'
    | '/contact'
    | '/hair-body'
    | '/skincare'
    | '/product/$productId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccessoriesRoute: typeof AccessoriesRoute
  BlogRoute: typeof BlogRoute
  CatalogRoute: typeof CatalogRoute
  ContactRoute: typeof ContactRoute
  HairBodyRoute: typeof HairBodyRoute
  SkincareRoute: typeof SkincareRoute
  ProductProductIdRoute: typeof ProductProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/skincare': {
      id: '/skincare'
      path: '/skincare'
      fullPath: '/skincare'
      preLoaderRoute: typeof SkincareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hair-body': {
      id: '/hair-body'
      path: '/hair-body'
      fullPath: '/hair-body'
      preLoaderRoute: typeof HairBodyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessories': {
      id: '/accessories'
      path: '/accessories'
      fullPath: '/accessories'
      preLoaderRoute: typeof AccessoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$productId': {
      id: '/product/$productId'
      path: '/product/$productId'
      fullPath: '/product/$productId'
      preLoaderRoute: typeof ProductProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccessoriesRoute: AccessoriesRoute,
  BlogRoute: BlogRoute,
  CatalogRoute: CatalogRoute,
  ContactRoute: ContactRoute,
  HairBodyRoute: HairBodyRoute,
  SkincareRoute: SkincareRoute,
  ProductProductIdRoute: ProductProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
